Check gh-issue- is int before checking range for better error
Invalid GitHub issue number! ('one-two')

instead of:

ValueError: invalid literal for int() with base 10: 'one-two'